title: Thai Asie Bordeaux
detail: Cuisine traditionelle. <wbr>Sur place, à emporter ou livré
email: thaiasie.bordeaux@gmail.com
phone: +33967741755
info: >
  La selection d'un *Entrée + Plat du jours + Accompagnement* et un tarif *Midi* (8.50€)<br/>
  <small>Valable uniquement le midi. Tarif *Midi* non présenté dans la liste de commande mais pris en compte lors du paiement.</small>

#markdown: kramdown
